version: "3.2"
services:
  web:
    env_file: 
      - ~/apps/libguru/shared/secrets.env
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    links:
      - postgres
    ports:
      - "4000:4000"

  postgres:
    image: postgres
    env_file: 
      - ~/apps/libguru/shared/secrets.env
    volumes: 
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"

  sso-proxy:
    image: a5huynh/oauth2_proxy
    env_file:
      - ~/apps/libguru/shared/secrets.env
    environment:
      VIRTUAL_HOST: libguru.internal.devguru.co
    links:
      - web
    ports:
      - "80:80"
    command: |
      --cookie-secure=false
      --upstream="http://web:4000"
      --http-address="0.0.0.0:80"
      --redirect-url="http://libguru.internal.devguru.co/oauth2/callback"
      --email-domain="netguru.pl"